apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    component: catalogue
    project: roboshop
    tier: app
data:
 MONGO: "true"
 MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: catalogue
 namespace: roboshop
 labels:
   component: catalogue
   project: roboshop
   tier: app
spec:
 replicas: 1
 selector:
   matchLabels:
     component: catalogue
     project: roboshop
     tier: app
 template:
   metadata:
     labels:
       component: catalogue
       project: roboshop
       tier: app
   spec:
     containers:
     - name: catalogue
       image: saicharan452/catalogue:v3
       envFrom:
        - configMapRef:
            name: catalogue
       resources:
         requests:
           memory: "128Mi"
           cpu: "50m"
         limits:
           memory: "256Mi"
           cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    component: catalogue
    project: roboshop
    tier: app
spec:
  selector:
    component: catalogue
    project: roboshop
    tier: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catalogue-hpa
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogue   # Name of the deployment to scale
  minReplicas: 2   # Minimum number of pods
  maxReplicas: 10  # Maximum number of pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10  # Target average CPU utilization percentage
