apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
data:
 CART_ENDPOINT: "cart:8080" 
 DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: shipping
 namespace: roboshop
 labels:
   component: shipping
   project: roboshop
   tier: app
spec:
 replicas: 1
 selector:
   matchLabels:
     component: shipping
     project: roboshop
     tier: app
 template:
   metadata:
     labels:
       component: shipping
       project: roboshop
       tier: app
   spec:
     containers:
     - name: shipping
       image: saicharan452/shipping:v3
       envFrom:
        - configMapRef:
            name: shipping
       resources:
         requests:
           memory: "256Mi"
           cpu: "100m"
         limits:
           memory: "512Mi"
           cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
spec:
  selector:
    component: shipping
    project: roboshop
    tier: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shipping-hpa
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping   # Name of the deployment to scale
  minReplicas: 2   # Minimum number of pods
  maxReplicas: 10  # Maximum number of pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10  # Target average CPU utilization percentage